### ISSUE TITLE
Swing support

### ISSUE THREAD

**Issue by moallemi** [bm1549/frigidaire#12]
Would you please add support for swing toggle?

![CleanShot 2022-08-16 at 19 24 08@2x](https://user-images.githubusercontent.com/1250691/185020956-0dfcc6a8-a8bd-449b-86aa-cc1867d5d86a.png)

**Comment by bm1549** [comment]
Unfortunately that's not a feature my units support so I'm not sure what the code for it would be in the API. If you figure it out, I'd happily accept a PR

**Comment by bm1549** [comment]
@moallemi could you try out the [test.py](https://github.com/bm1549/frigidaire/blob/main/test.py) script and see if you can set the field via [VERTICAL_SWING](https://github.com/bm1549/frigidaire/blob/main/frigidaire/__init__.py#L54)? The component value is likely to be the same as what's present in your [applicationDetails](https://github.com/bm1549/frigidaire/blob/main/test.py#L48)
