### ISSUE TITLE
urllib3-1.26.42 doesn't exist yet

### ISSUE THREAD

**Issue by fabaff** [bm1549/frigidaire#14]
https://github.com/bm1549/frigidaire/blob/ab6209c7fb0d176cfa60cca6eb2d25c7bede1b20/setup.py#L32

Latest urllib3 release at 2023-04-11 is [1.26.15](https://github.com/urllib3/urllib3/releases/tag/1.26.15).

**Comment by bm1549** [comment]
Updated to use `1.26.4`
