### ISSUE TITLE
Tagged releases and tarball on PyPI still contains SNAPSHOT

### ISSUE THREAD

**Issue by fabaff** [bm1549/frigidaire#15]
https://github.com/bm1549/frigidaire/blob/ab6209c7fb0d176cfa60cca6eb2d25c7bede1b20/setup.py#L8

The tagged releases on GitHub still contain `SNAPSHOT` instead of the actual release. This also applies for the tarballs which are published on PyPI. This is an issue for all distributions as it requires them to patch the `version`.

In the near future the module is also no longer installable for Home Assistant users.

**Comment by fabaff** [comment]
The release flow doesn't seem to work.

```bash
$ curl https://files.pythonhosted.org/packages/4b/19/e1e3df057e4022a86fa688663472078ed9d7c3b5ee3d396d7fa2bebdef15/frigidaire-0.18.5.tar.gz -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6622  100  6622    0     0  57412      0 --:--:-- --:--:-- --:--:-- 57582
$ tar -xzf frigidaire-0.18.5.tar.gz 
$ cat frigidaire-0.18.5/setup.py | grep -e version
version = "SNAPSHOT"
if "--version" in sys.argv:
    idx = sys.argv.index("--version")
    version = sys.argv.pop(idx)
print("Using version " + version)
    version=version,
``

**Comment by bm1549** [comment]
Thanks for reporting @fabaff - can you confirm that `0.18.10` resolves the issue you're seeing?
