### ISSUE TITLE
Cut new release to unblock dehumidifier support downstream

### ISSUE THREAD

**Issue by rothn** [bm1549/frigidaire#26]
A downstream PR https://github.com/bm1549/home-assistant-frigidaire/pull/50 is blocked because features it depends on are not available in the x.15 release. It may be helpful for dehumidifier owners to run the appropriate testing and deploy a new release to unblock that PR. I would be happy to help.

**Comment by bm1549** [comment]
Released via Released as part of [0.18.16](https://pypi.org/project/frigidaire/0.18.16/)
