### ISSUE TITLE
Install Instructions? Alternatively, HACS manifest?

### ISSUE THREAD

**Issue by applehat** [bm1549/frigidaire#3]
So, I feel like an idiot -- I can't figure out how to add this as a custom component.

I looked at the PR into HA, and it seems like there are a lot more to the integration then what is in this repo.

I've tried dropping it into my custom_components folder (I have other custom components that work, installed from HACS) but I'm not seeing anything.

The readme also mentions HomeKit -- Does it integrate as a homekit device?

Sorry for the stupid questions, but after playing around for an hour I'm lost.

**Comment by applehat** [comment]
OK -- im realizing now that this isn't a custom component, but instead a piece thats included in the HA integration.

I guess I'll just wait for them to merge it (tried copying the files from your branch into custom components with no luck.

**Comment by bm1549** [comment]
@applehat I've just created a new repo along with installation instructions for registering this as a custom component:
https://github.com/bm1549/home-assistant-frigidaire

**Comment by applehat** [comment]
Awesome. Thanks man!

Hopefully you get merged into Core soon

**Comment by theglus** [comment]
@applehat I added the repo to HACs as a custom repository which made install a breeze.
